apiVersion: v1
kind: Namespace
metadata:
  name: f4space
---
# MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-apigateway-pvc
  namespace: f4space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-apigateway
  namespace: f4space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-apigateway
  template:
    metadata:
      labels:
        app: mysql-apigateway
    spec:
      containers:
        - name: mysql-apigateway
          image: mysql:9.2.0
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: "f4space"
          args:
            - "--lower_case_table_names=1"
            - "--character_set_server=utf8mb4"
            - "--explicit_defaults_for_timestamp"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-apigateway-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: mysql-apigateway-storage
          persistentVolumeClaim:
            claimName: mysql-apigateway-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-apigateway
  namespace: f4space
spec:
  selector:
    app: mysql-apigateway
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
